name: Update

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  update:
    name: Update bundle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - uses: actions/checkout@v2

    - name: Run go generate
      run: go generate

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update ${{ steps.date.outputs.date }}"
        tagging_message: "${{ steps.date.outputs.date }}"
