name: Update

on:
  schedule:
  - cron: '* * * * *'

jobs:
  update:
    name: Update bundle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - uses: actions/checkout@v2
      with:
        ref: test-update

    - name: Run go generate
      run: go generate

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update $(date +%Y.%m.%d)"
